### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by supern64** [BananaCakeComputer/PyongyangRacer#1]
Hey, I managed to find 2 of the 11 missing images from some cached files:
26.png: ![26](https://github.com/BananaCakeComputer/PyongyangRacer/assets/41817899/4c586348-0b02-46d6-99f2-c61b8f5c17e7)
30.png: ![30](https://github.com/BananaCakeComputer/PyongyangRacer/assets/41817899/13a45793-2212-4ac5-a66c-57ec8e3a1b33)

I don't think I'll have any better luck finding the rest though as they were never archived nor were they ever loaded...

**Comment by supern64** [comment]
Update: I found them. https://github.com/cursedastronaut/Pyongyang-Racer-60FPS/tree/main/photo

**Comment by BananaCakeComputer** [comment]
I had uploaded the photo file folder to this repository, thanks for creating an issue
